# Generated by Django 4.1.4 on 2023-07-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katzegram', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
