# Generated by Django 4.1.4 on 2023-07-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katzegram', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
