# Generated by Django 4.1.4 on 2023-07-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katzegram', '0008_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
