# Generated by Django 4.1.4 on 2023-07-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katzegram', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
